#!/usr/bin/env python3
"""Landmark buildings: a real building extruded from an OSM floor plan, instead of the
standard station house swept along the line.

Everything on the line (tunnels, viaducts, platforms) is generated by sweeping a
cross-section along the center line, but a station building above ground is not: it is
an arbitrary polygon that has to be rasterized, walled and roofed on its own.

The BlockSink implementation (infrastructure's World) automatically drops blocks that do
not belong to the current region, so this module only has to call build() once for each
region a bbox covers and can leave the clipping to it.

Self-test: ./.venv/bin/python -m tests.test_landmarks
"""
import collections
import os, math, json

from mrt import config
from mrt.application import build_concourse as BCC
from mrt.application import build_exits as BX
from mrt.application.build_concourse import ShaftStair
from mrt.domain import exits as EX
from mrt.domain import geometry as shapes

AIR = "minecraft:air"

# Taipei Main Station complex: the underground malls serve both Taipei Main Station and
# Beimen (the west end of Taipei City Mall is at Beimen station), and Zhongshan Metro Mall
# runs all the way to Zhongshan and Shuanglian. In reality these stations' exits open onto
# the underground malls, and pulling a separate stair shaft for each would dig through the
# mall, so they are all left to the underground mall.
COMPLEX = ("台北車站", "北門", "中山", "雙連")
INDOOR_R = 1500        # passage collection radius; Zhongshan Metro Mall reaches Shuanglian


class Building:
    """A multi-story building extruded from a floor plan polygon, with an optional hip roof.

    poly      : [(mc_x, mc_z), ...] floor plan
    g0        : ground y (the first-floor slab)
    storeys   : number of stories above ground
    storey_h  : story height (meters)
    """

    def __init__(self, poly, g0, storeys=1, storey_h=5,
                 wall="minecraft:smooth_sandstone",
                 floor="minecraft:polished_andesite",
                 roof="minecraft:deepslate_tiles",
                 ridge=None, glass="minecraft:glass_pane",
                 lamp="minecraft:sea_lantern",
                 roof_slope=0.55, roof_max=None, eaves=1,
                 hollow=True, name=None, doors=(), open_core=0, found=3,
                 core_inset=8, wall_inset=0, columns=(), col_half=1,
                 body_poly=None, core_poly=None,
                 checker=None, trim=None):
        self.poly = [(float(x), float(z)) for x, z in poly]
        self.g0, self.storeys, self.storey_h = int(g0), int(storeys), int(storey_h)
        self.wall, self.floor, self.roof = wall, floor, roof
        self.ridge = ridge or roof
        self.glass, self.lamp = glass, lamp
        self.roof_slope, self.roof_max, self.eaves = roof_slope, roof_max, int(eaves)
        self.hollow, self.name = hollow, name
        self.doors = [(int(x), int(z)) for x, z in doors]
        self.open_core = int(open_core)      # no floor slab on the first N stories: a tall hall
        self.found = int(found)              # how many blocks the foundation goes down
        self.core_inset = int(core_inset)    # cells from the outer wall to the open core
        self.body_poly = body_poly           # main structure (intersected with the eaves outline)
        self.core_poly = core_poly           # extent of the tall hall
        self.wall_inset = int(wall_inset)    # outer wall setback from the eaves (the overhang)
        self.columns = [(int(x), int(z)) for x, z in columns]
        self.col_half = int(col_half)
        self.checker = checker               # (color A, color B) -> first-floor checkerboard
        self.trim = trim or roof
        self._cells = None

    # ---- Geometry ----
    @property
    def cells(self):
        if self._cells is None:
            self._cells = shapes.poly_cells(self.poly)
        return self._cells

    def bbox(self):
        x0, z0, x1, z1 = shapes.bbox(self.poly)
        m = self.eaves + 2
        return (int(x0) - m, int(z0) - m, int(x1) + m, int(z1) + m)

    def top_y(self):
        return self.g0 + self.storeys * self.storey_h

    # ---- Writing ----
    def build(self, w):
        cells = self.cells
        if not cells:
            return
        # The eaves reach beyond the main structure: the OSM floor plan measures the outer
        # edge of the eaves and canopies (158x127 m), while the main structure is only
        # 149x110 m. The difference is an overhang of about 4 m on each side.
        if self.body_poly is not None:
            body = cells & shapes.poly_cells(self.body_poly)
        elif self.wall_inset:
            body = shapes.inset(cells, self.wall_inset)
        else:
            body = cells
        if not body:
            body = cells
        ring = shapes.ring_cells(body)
        inner = body - ring
        core = (body & shapes.poly_cells(self.core_poly)) if self.core_poly is not None \
            else shapes.inset(body, self.core_inset)
        g0, sh, n = self.g0, self.storey_h, self.storeys

        for x, z in body:
            for y in range(g0 - self.found, g0):
                w.set(x, y, z, self.floor)

        for k in range(n):
            fy = g0 + k * sh
            if k == 0 or k >= self.open_core:
                for x, z in body:
                    w.set(x, fy, z, self.floor)
            else:
                # Open in the middle, leaving only the gallery along the outer wall.
                for x, z in body:
                    w.set(x, fy, z, AIR if (x, z) in core else self.floor)
            for x, z in ring:
                for dy in range(1, sh):
                    y = fy + dy
                    win = 2 <= dy <= sh - 2 and ((x + z) % 4) != 0
                    w.set(x, y, z, self.glass if win else self.wall)
            if self.hollow:
                for x, z in inner:
                    for dy in range(1, sh):
                        w.set(x, fy + dy, z, AIR)
                for x, z in inner:
                    if x % 8 == 0 and z % 8 == 0 and (x, z) not in core:
                        w.set(x, fy + sh - 1, z, self.lamp)

        # Black-and-white diagonal checkerboard paving on the first floor. The real one was
        # laid in 2011, at 45 degrees to the building axis, with squares about 3 m across:
        # (x+z)//4 and (x-z)//4 give exactly a grid rotated 45 degrees, about 2.8 m on the
        # diagonal.
        if self.checker:
            ca, cb = self.checker
            for x, z in body:
                w.set(x, g0, z, ca if (((x + z) // 4 + (x - z) // 4) % 2) else cb)

        # Freestanding columns in the hall: 2 rows x 4, each about 1.35 m across.
        top = g0 + min(self.open_core, n) * sh
        for cxx, czz in self.columns:
            for dx in range(-self.col_half, self.col_half + 1):
                for dz in range(-self.col_half, self.col_half + 1):
                    if (cxx + dx, czz + dz) not in body:
                        continue
                    for y in range(g0 + 1, top):
                        w.set(cxx + dx, y, czz + dz, self.floor)

        ty = self.top_y()
        for x, z in body:
            w.set(x, ty, z, self.floor)
        for x, z in cells - body:          # the overhang
            w.set(x, ty, z, self.trim)
        if self.eaves:
            eave = set()
            for x, z in shapes.ring_cells(cells):
                for dx in range(-self.eaves, self.eaves + 1):
                    for dz in range(-self.eaves, self.eaves + 1):
                        if (x + dx, z + dz) not in cells:
                            eave.add((x + dx, z + dz))
            for x, z in eave:
                w.set(x, ty, z, self.trim)

        for dx, dz in self.doors:
            for x in range(dx - 2, dx + 3):
                for z in range(dz - 2, dz + 3):
                    if (x, z) in ring:
                        for y in range(g0 + 1, g0 + 5):
                            w.set(x, y, z, AIR)

        # Truncated hip roof: the four slopes end at a flat top platform instead of meeting
        # in a pyramid point. The platform forms naturally once hip_roof's max_rise clamps.
        rf = shapes.hip_roof(cells, ty + 1, self.roof_slope, self.roof_max)
        peak = max(v[1] for v in rf.values())
        for (x, z), (y0, y1) in rf.items():
            for y in range(y0, y1 + 1):
                w.set(x, y, z, self.trim if (y == y0 and y1 > y0) else self.roof)
        for (x, z), (y0, y1) in rf.items():
            if y1 == peak:
                w.set(x, peak, z, self.roof)
        if self.hollow:
            for (x, z), (y0, y1) in rf.items():
                if (x, z) in inner:
                    for y in range(ty + 1, y1):
                        w.set(x, y, z, AIR)


class Slab:
    """A horizontal floor slab or underground hall, used to join the concourses of several lines."""

    def __init__(self, poly, y, thick=1, mat="minecraft:polished_andesite",
                 clear=0, wall=None, lamp="minecraft:sea_lantern", lamp_every=8):
        self.poly = [(float(x), float(z)) for x, z in poly]
        self.y, self.thick, self.mat = int(y), int(thick), mat
        self.clear, self.wall = int(clear), wall
        self.lamp, self.lamp_every = lamp, int(lamp_every)
        self._cells = None

    @property
    def cells(self):
        if self._cells is None:
            self._cells = shapes.poly_cells(self.poly)
        return self._cells

    def bbox(self):
        x0, z0, x1, z1 = shapes.bbox(self.poly)
        return (int(x0) - 2, int(z0) - 2, int(x1) + 2, int(z1) + 2)

    def build(self, w):
        cells = self.cells
        ring = shapes.ring_cells(cells)
        for x, z in cells:
            for y in range(self.y - self.thick + 1, self.y + 1):
                w.set(x, y, z, self.mat)
        if self.clear:
            for x, z in cells:
                for y in range(self.y + 1, self.y + 1 + self.clear):
                    w.set(x, y, z, AIR)
            if self.wall:
                for x, z in ring:
                    for y in range(self.y + 1, self.y + 1 + self.clear):
                        w.set(x, y, z, self.wall)
            for x, z in cells:
                if x % self.lamp_every == 0 and z % self.lamp_every == 0 \
                        and (x, z) not in ring:
                    w.set(x, self.y + self.clear, z, self.lamp)
            # Roof slab.
            for x, z in cells:
                w.set(x, self.y + self.clear + 1, z, self.mat)


class Passage:
    """A horizontal passage between two points: dug out, walled, paved and lit."""

    def __init__(self, x0, z0, x1, z1, y, half_w=2, head=3,
                 floor="minecraft:polished_andesite",
                 wall="minecraft:gray_concrete",
                 lamp="minecraft:sea_lantern"):
        self.a = (int(x0), int(z0)); self.b = (int(x1), int(z1))
        self.y, self.half_w, self.head = int(y), int(half_w), int(head)
        self.floor, self.wall, self.lamp = floor, wall, lamp

    def bbox(self):
        m = self.half_w + 2
        return (min(self.a[0], self.b[0]) - m, min(self.a[1], self.b[1]) - m,
                max(self.a[0], self.b[0]) + m, max(self.a[1], self.b[1]) + m)

    def build(self, w):
        (x0, z0), (x1, z1) = self.a, self.b
        n = int(max(abs(x1 - x0), abs(z1 - z0)))
        if n == 0:
            return
        ux, uz = (x1 - x0) / n, (z1 - z0) / n
        px, pz = -uz, ux                       # normal
        H = self.half_w
        for t in range(n + 1):
            cx, cz = x0 + ux * t, z0 + uz * t
            for b in range(-H - 1, H + 2):
                x, z = int(round(cx + px * b)), int(round(cz + pz * b))
                side = abs(b) == H + 1
                w.set(x, self.y - 1, z, self.floor)
                for dy in range(0, self.head + 1):
                    y = self.y + dy
                    if side or dy == self.head:
                        w.set(x, y, z, self.wall)
                    else:
                        w.set(x, y, z, AIR)
            if t % 10 == 0:
                x, z = int(round(cx)), int(round(cz))
                w.set(x, self.y + self.head - 1, z, self.lamp)


class RailHall:
    """A multi-platform underground station hall (like the Taiwan Railway and High Speed Rail
    one), laid out along the real platform center lines."""

    def __init__(self, plats, y, poly, half_w=5, clear=8,
                 plat="minecraft:polished_diorite",
                 edge="minecraft:yellow_concrete",
                 deck="minecraft:smooth_stone",
                 wall="minecraft:deepslate_bricks",
                 lamp="minecraft:sea_lantern"):
        self.plats = [[(float(x), float(z)) for x, z in g] for g in plats]
        self.y, self.poly = int(y), [(float(x), float(z)) for x, z in poly]
        self.half_w, self.clear = int(half_w), int(clear)
        self.plat, self.edge, self.deck = plat, edge, deck
        self.wall, self.lamp = wall, lamp
        self._cells = None

    @property
    def cells(self):
        if self._cells is None:
            self._cells = shapes.poly_cells(self.poly)
        return self._cells

    def bbox(self):
        x0, z0, x1, z1 = shapes.bbox(self.poly)
        return (int(x0) - 3, int(z0) - 3, int(x1) + 3, int(z1) + 3)

    def build(self, w):
        cells = self.cells
        if not cells:
            return
        ring = shapes.ring_cells(cells)
        y = self.y
        # Box: base slab, excavation, roof slab, surrounding walls.
        for x, z in cells:
            w.set(x, y - 1, z, self.wall)
            for dy in range(0, self.clear + 1):
                w.set(x, y + dy, z, self.wall if dy == self.clear else AIR)
            w.set(x, y, z, self.deck)          # track bed
        for x, z in ring:
            for dy in range(0, self.clear):
                w.set(x, y + dy, z, self.wall)
        # Platforms. OSM platform ways are mostly **closed outlines**, not center lines:
        # brushing a radius along them turns an 8.5 m wide platform 18 m wide and glues
        # the four together. Closed ones are filled as polygons, which gives the real
        # shape; only open ones fall back to brushing along the line.
        for g in self.plats:
            if len(g) > 3 and abs(g[0][0]-g[-1][0]) < 1e-6 and abs(g[0][1]-g[-1][1]) < 1e-6:
                band = shapes.poly_cells(g)
            else:
                band = set()
                for i in range(len(g) - 1):
                    ax, az = g[i]; bx, bz = g[i + 1]
                    n = int(max(abs(bx - ax), abs(bz - az))) or 1
                    for t in range(n + 1):
                        cx, cz = ax + (bx-ax)*t/n, az + (bz-az)*t/n
                        for dx in range(-self.half_w, self.half_w + 1):
                            for dz in range(-self.half_w, self.half_w + 1):
                                if dx*dx + dz*dz <= self.half_w**2:
                                    band.add((int(round(cx))+dx, int(round(cz))+dz))
            band &= cells
            rim = shapes.ring_cells(band)
            for x, z in band:
                w.set(x, y + 1, z, self.edge if (x, z) in rim else self.plat)
                for dy in range(2, self.clear):
                    w.set(x, y + dy, z, AIR)
            for x, z in band:
                if x % 12 == 0 and z % 12 == 0:
                    w.set(x, y + self.clear - 1, z, self.lamp)
# ---------- World-level landmark list ----------

def for_world(segs, stations, terr, colours=None):
    """Return (landmark list, real exits). build_world buckets the landmarks by bbox() and
    then calls build(w) for each region they cover.

    Real exits cover every station in the network (underground, elevated and at-grade),
    and the two station boxes of a transfer station are also joined by a transfer
    passage. The Taipei Main Station complex (COMPLEX) is the exception: people enter,
    leave and transfer there through the underground malls.

    segs     : the segments planned by build_world (with samples / ys / ground / stn / hw)
    stations : list of (refs, Chinese name, mc_x, mc_z, English name, ref string)
    terr     : Terrain, for looking up ground elevation
    colours  : {line: "#rrggbb"}, the line colors on exit signs (None gives the old
               plain-text signs)

    The real exits are {(segment index, sample index): number of shafts}. A station with
    real exits no longer gets the template stairs, and the cli uses this table to turn
    them off.
    """
    out = []
    tm, leftover = taipei_main(segs, stations, terr)
    out += tm
    # Exits around Taipei Main Station are handled by the underground malls; the other
    # underground stations are built from entrances.json. Exits in the complex stations
    # that the underground mall cannot reach are also handed over here, each connected
    # into its own station box. The underground mall's floor and stairs claim their space
    # first, so that the shafts and passages built later do not dig through it.
    by_name = collections.defaultdict(list)
    for e in _load("entrances.json"):
        if e.get("source") == "near_station" or not e.get("station"):
            continue                    # an ordinary building entrance, not a metro exit
        if e["station"] in COMPLEX:
            continue
        ref = str(e.get("ref") or e.get("name_zh") or e.get("name") or "")
        by_name[e["station"]].append((ref, int(e["mc_x"]), int(e["mc_z"])))
    for name, lst in leftover.items():
        by_name[name] = lst
    ex_objs, exits, _ = BX.station_exits(
        segs, by_name, lambda x, z: int(terr.y_at(x, z)),
        used=BX.footprint(tm), no_transfer=COMPLEX, no_default=COMPLEX, colours=colours)
    out += ex_objs
    # The underground station boxes of the complex stations are reached by the underground
    # mall's link stairs, so their template stairs must be turned off: such a stair climbs
    # from the concourse all the way to the ground and passes right through the mall
    # level, with its treads lying across the passage and blocking it. That is how the
    # Songshan-Xindian Line platform at Zhongshan became unreachable from the underground
    # mall.
    from mrt.domain.alignment import structure_for_ground
    for li, sg in enumerate(segs):
        for bi, (full, name, en) in sg["stn"].items():
            if name in COMPLEX and structure_for_ground(
                    int(sg["ys"][bi]), int(sg["ground"][bi])) == "tunnel":
                exits.setdefault((li, bi), 0)
    return out, exits


def _load(name):
    f = os.path.join(config.DATA, name)
    if not os.path.exists(f):
        return []
    return json.load(open(f, encoding="utf-8"))["items"]


def _station_on_lines(segs, zh, underground_only=False):
    """Find a station's position on each line: {ref: (x, z, ux, uz, rail top y)}."""
    from mrt.domain.alignment import structure_for_ground
    out = {}
    for sg in segs:
        for bi, (full, nm, en) in sg["stn"].items():
            if nm == zh and sg["ref"] not in out:
                x, z, ux, uz, _ = sg["samples"][bi]
                y, g = int(sg["ys"][bi]), int(sg["ground"][bi])
                if underground_only and structure_for_ground(y, g) != "tunnel":
                    continue
                out[sg["ref"]] = (x, z, ux, uz, y)
    return out


def _axes(poly):
    """The major and minor axes of a polygon (unit vectors), used to place the column grid
    on the building's own grid."""
    import numpy as np
    g = np.array(poly, dtype=float)
    d = g - g.mean(0)
    vt = np.linalg.svd(d, full_matrices=False)[2]
    return [(float(vt[0][0]), float(vt[0][1])), (float(vt[1][0]), float(vt[1][1]))]


def taipei_main(segs, stations, terr):
    """The Taipei Main Station complex.

    All of its geometry comes from real data, not estimates:
      · The station building floor plan is OSM way 23641610 (25 vertices, about
        20,000 m2), tagged building:levels=7, height=30, roof:shape=pyramidal,
        roof:height=18
      · The doors open at the OSM nodes for the South 1-3, North 1-3, East 1 and 3, and
        West 1 and 3 gates
      · The railway and HSR platforms use OSM's four platform center lines (level=-2,
        about 327 m each)
      · The exits use the actual coordinates of the OSM subway_entrance nodes (M1-M8 and
        others)
      · The vertical order of the metro platforms is restored by the tunnel_layers pins
        (Bannan Line at B3, Tamsui-Xinyi Line at B4)
    """
    blds = _load("station_buildings.json")
    tp = [b for b in blds if (b.get("name_zh") or b.get("name")) == "臺北車站"]
    if not tp:
        return [], {}
    b = tp[0]
    poly = [(p[0], p[1]) for p in b["polygon"]]
    cx, cz = shapes.centroid(poly)
    g0 = int(terr.y_at(cx, cz))

    ents = _load("entrances.json")
    doors = [(e["mc_x"], e["mc_z"]) for e in ents
             if str(e.get("ref") or "").endswith("門")
             and abs(e["mc_x"] - cx) < 160 and abs(e["mc_z"] - cz) < 160]

    out = []

    # ---- 1. The station building above ground ----
    # height=30 cannot hold 7 stories and still leave an 18 m roof, so 30 is taken as the
    # eaves height with the 18 m roof on top (30 m eaves + 18 m roof = 48 m, consistent
    # with what the column grid in the Taiwan Railway drawings implies).
    #
    # The roof is a **truncated hip roof of red-brick-colored clay tiles with white trim**
    # (the four slopes end at a flat top platform), not dark gray and not a pointed
    # pyramid: clamping the rise with roof_max forms the platform naturally.
    #
    # The 158x127 m that OSM measures is the outer edge of the eaves and canopies; the main
    # structure is 149x110 m (the Taiwan Railway drawings give an 8.75 m column grid: 17
    # bays east-west, and 12 bays north-south plus a narrow 5.3 m central bay). So the
    # outer wall is set back 4 cells, and the difference is the overhanging eaves.
    ax = _axes(poly)
    rot = math.atan2(ax[0][1], ax[0][0])
    # Taiwan Railway drawings: 8.75 m column grid, 17 bays east-west = 148.75 m, 12 bays
    # north-south plus the 5.3 m central narrow bay = 110.3 m. OSM measures 169x141 m along
    # the main axes; the excess is the eaves and the ground-level canopies, so the
    # intersection cuts the main structure back to the official dimensions.
    body_poly = shapes.rect(cx, cz, 148.75, 110.3, rot)
    core_poly = shapes.rect(cx, cz, 61.25, 40.30, rot)   # inside the ticket hall's columns
    cols = []
    for r in (-20.15, 20.15):                       # two rows 40.3 m apart
        for c in (-26.25, -8.75, 8.75, 26.25):      # columns 17.5 m apart within a row
            cols.append((round(cx + ax[0][0]*c + ax[1][0]*r),
                         round(cz + ax[0][1]*c + ax[1][1]*r)))
    out.append(Building(
        poly, g0, storeys=7, storey_h=4,
        wall="minecraft:smooth_sandstone",
        floor="minecraft:polished_andesite",
        roof="minecraft:bricks",
        trim="minecraft:white_concrete",
        glass="minecraft:light_gray_stained_glass_pane",
        roof_slope=0.5, roof_max=18, eaves=2,
        doors=doors, open_core=7, body_poly=body_poly, core_poly=core_poly,
        columns=cols, col_half=1,
        checker=("minecraft:black_concrete", "minecraft:white_concrete"),
        found=8, name="臺北車站"))

    # ---- 2. The B1 hall ----
    b1 = g0 - 7
    out.append(Slab(shapes.rect(cx, cz, 150, 120), b1, clear=4,
                    wall="minecraft:deepslate_bricks"))

    # ---- 3. The railway and HSR platform level ----
    rail_hall_y = None
    plats = [p["geometry"] for p in _load("platform_levels.json")
             if p.get("station") == "台北車站" and str(p.get("level")) == "-2"
             and p.get("ref") in ("1", "2", "3", "4")]
    if plats:
        xs = [q[0] for g in plats for q in g]; zs = [q[1] for g in plats for q in g]
        hall = [(min(xs) - 10, min(zs) - 12), (max(xs) + 10, min(zs) - 12),
                (max(xs) + 10, max(zs) + 12), (min(xs) - 10, max(zs) + 12)]
        out.append(RailHall(plats, g0 - 17, hall, half_w=4, clear=7))
        rail_hall_y = g0 - 16          # standing surface of the railway and HSR hall

    # ---- 4. Underground malls: built along OSM's passage center lines, joining every exit ----
    # This used to pull a stair shaft from each exit to the nearest target. The targets did
    # not connect to each other, so the result was fourteen separate holes. It now builds
    # the underground mall network that OSM actually maps: around Taipei Main Station there
    # are 7.7 km of passage center lines (Taipei City Mall, Station Front Metro Mall,
    # Zhongshan Metro Mall, the Caesar food court, and the M and K zone concourses), and
    # building along them yields a connected network from the start.
    ways = [w for w in _load("indoor.json")
            if math.hypot(w["mc_x"] - cx, w["mc_z"] - cz) <= INDOOR_R]
    picked = [(str(e.get("ref") or ""), e["mc_x"], e["mc_z"]) for e in ents
              if e.get("station") in COMPLEX and str(e.get("ref") or "")
              and math.hypot(e["mc_x"] - cx, e["mc_z"] - cz) <= INDOOR_R]
    station_of = {(e["mc_x"], e["mc_z"]): e["station"] for e in ents
                  if e.get("station") in COMPLEX}
    # Every complex station needs a link stair to its concourse on every underground line.
    # This used to connect only Taipei Main Station's own three lines, and the
    # Songshan-Xindian Line platform at Beimen could not be reached from the underground
    # mall at all.
    links = []
    for name in COMPLEX:
        for ref, (sx, sz, ux, uz, ty) in _station_on_lines(
                segs, name, underground_only=True).items():
            tag = ref if name == "台北車站" else f"{ref}@{name}"
            links.append((sx, sz, ty + 7, tag, ux, uz))
    if rail_hall_y is not None:
        # The railway and HSR hall must be connected as well: in reality the underground
        # mall at Taipei Main Station leads first to the Taiwan Railway B1 hall, and from
        # there down to the platforms.
        links.append((cx, cz, rail_hall_y, "TRA", 1.0, 0.0))

    hall_cells = shapes.poly_cells(shapes.rect(cx, cz, 150, 120))
    # The link stair shafts must avoid other lines' station boxes and tunnels (the
    # occupancy table's tags are segment indices; a shaft bottom inside its own line's
    # station box is expected).
    occ = EX.index_segments(segs)

    def own_tags(tag):
        ref = tag.split("@")[0]
        return {li for li, sg in enumerate(segs) if sg["ref"] == ref}

    objs, rep = BCC.plan(ways, picked, lambda x, z: int(terr.y_at(x, z)),
                         b1 + 1, links=links, near=(cx, cz),
                         no_wall=hall_cells, occ=occ, own_tags=own_tags)
    for o in objs:
        o.underground = True        # no terrain generation needed; see cli/build_world
    out += objs
    print(f"  Taipei Main Station underground malls: {rep['length']:,} m of passages, "
          f"{rep['cells']:,} floor cells, {len(rep['exits'])} exit stairs"
          + (f", {len(rep['orphan'])} not connected" if rep["orphan"] else ""))
    for nm, sx0, sz0, yto, yg0, clash in rep["links"]:
        print(f"    Link stair shaft {nm:<8} ({sx0},{sz0})  "
              f"mall y{yg0 + 1} -> concourse y{yto}"
              + (f"  warning: the shaft still passes through {clash} cells "
                 f"of another line's structure" if clash else ""))

    # Exits that cannot reach the underground mall (OSM has no passages mapped there) fall
    # back to the old approach: a stair shaft down to the B1 hall. The underground mall
    # reaches the hall itself, so they are still connected. This is limited to 260 m: for
    # the ones farther away (the few west of Beimen), OSM has no passages in that area at
    # all, and forcing a 600 m passage out to them would only bore through everything
    # along the way. Those are handed back to the regular station exit planning
    # (build_exits), each connected into its own station box.
    leftover = collections.defaultdict(list)
    handled = 0
    for r, ex, ez in rep["orphan"]:
        eg = int(terr.y_at(ex, ez))
        d = math.hypot(cx - ex, cz - ez)
        if d <= 260 and handled < 8 and d >= 12 and b1 + 1 < eg - 4:
            ux, uz = (cx - ex) / d, (cz - ez) / d
            if abs(ux) >= abs(uz):
                dx, dz = (1 if ux > 0 else -1), 0
            else:
                dx, dz = 0, (1 if uz > 0 else -1)
            out.append(ShaftStair(ex, ez, dx, dz, eg, b1 + 1))
            bx = ex + dx * (ShaftStair.FLIGHT + 2)
            bz = ez + dz * (ShaftStair.FLIGHT + 2)
            out.append(Passage(bx, bz, cx, cz, b1 + 1))
            handled += 1
            continue
        st = station_of.get((int(ex), int(ez)))
        if st:
            leftover[st].append((r, int(ex), int(ez)))
    return out, leftover
